mtail:
  image: dylanmei/mtail
  command: -progs /etc/mtail -logs /var/log/haproxy/haproxy.log -v 3 -alsologtostderr
  ports:
    - 3903:3903
  volumes:
    - ./logs:/var/log/haproxy
    - ./haproxy.mtail:/etc/mtail/haproxy.mtail
haproxy:
  build: .
  dockerfile: Dockerfile.haproxy
  command: /start
  ports:
    - 8080:80
    - 3000:3000
  links:
    - muxy:webapp
  volumes:
    - ./logs:/var/log/haproxy
muxy:
  image: dylanmei/muxy
  command: proxy --config /etc/muxy.yml
  expose:
    - 5000
  links:
    - webapp
  volumes:
    - ./muxy.yml:/etc/muxy.yml
webapp:
  image: training/webapp
  expose:
    - 5000
prometheus:
  image: prom/prometheus
  command: -config.file=/etc/prometheus.yml
  ports:
    - 9090:9090
  links:
    - mtail
  volumes:
    - ./prometheus.yml:/etc/prometheus.yml
